docker-deploy/web-app/project1/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('ridesharer/', include('ridesharer.urls')),
    path('admin/', admin.site.urls),
]

docker-deploy/web-app/ridesharer/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'ridesharer'
urlpatterns = [
    #path('<int:question_id>/vote/', views.vote, name='vote'),
    path('login', views.user_login, name='user_login'),
    path('register', views.user_register, name='user_register'),
    path('home', views.user_home, name='user_home'),
    path('logout', views.user_logout, name='user_logout'),
    path('driver_register',login_required(views.driver_register.as_view()), name='driver_register'),
    path('vehicle_info', views.vehicle_update, name='vehicle_info'),
    path('vehicle_delete', views.vehicle_delete, name='vehicle_delete'),
    path('user_info', views.user_update, name='user_update'),
    path('ride_create', login_required(views.ride_create.as_view()), name='ride_create'),
    path('ride_list',  views.ride_list, name='ride_list'),
    path('joined_ride_list',  views.joined_ride_list, name='joined_ride_list'),
    path('joined_ride_detail/<int:ride_id>',  views.joined_ride_detail, name='joined_ride_detail'),
    path('<int:ride_id>/ride_delete',  views.ride_delete, name='ride_delete'),
    path('order_list',  views.order_list, name='order_list'),
    path('<int:ride_id>/', views.ride_detail, name='ride_detail'),
    path('<int:ride_id>/confirm', views.ride_confirm, name='ride_confirm'),
    path('search_rides_for_driver', views.search_rides_for_driver, name='search_rides_for_driver'),
    path('search_rides_for_sharer', views.search_rides_for_sharer, name='search_rides_for_sharer'),
    path('<int:ride_id>/<int:passengers_num>/confirm_join', views.confirm_join, name='confirm_join')
]

docker-deploy/web-app/ridesharer/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
# Create your models here.

class VehicleType(models.TextChoices):
    SUV = 'S', 'SUV'
    MINIBUS = 'M', 'MiniBus'
    BABYCAR = 'B', 'Baby Car'
    NORMALCAR = 'N', 'Normal Car'

class Vehicle(models.Model):
    id = models.AutoField(primary_key = True)
    driver = models.OneToOneField(
        User, on_delete=models.CASCADE, primary_key=False, related_name='vehicle')

    vehicle_type = models.CharField(max_length=1, choices=VehicleType.choices, default=VehicleType.NORMALCAR)
    license_number = models.CharField(max_length = 50)
    max_capacity = models.PositiveIntegerField(default = 1)
    special_info = models.CharField(max_length = 100,null=False, blank = True)
    def __str__(self):
        return self.vehicle_type + "Driver: " + self.driver.username

    def get_absolute_url(self):
        return reverse('ridesharer:vehicle_info')

class RideStatus(models.TextChoices):
    OPEN = 'O', 'open'
    CONFIRMED = 'C', 'confirmed'
    FINISH = 'F', 'finish'

class Ride(models.Model):
    id = models.AutoField(primary_key = True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE,primary_key=False, related_name='ride')
    driver = models.ForeignKey(User, on_delete=models.CASCADE,primary_key=False, related_name='driver_ride',null=True)
    require_arrival_time = models.DateTimeField('arrival time',help_text='eg.2077-01-01 12:00')
    require_vehicle_type = models.CharField(max_length=1, choices=VehicleType.choices, default='', blank=True)
    create_time = models.DateTimeField('ride created date',null=True, blank=True)
    destination = models.CharField(max_length=200)
    passengers = models.PositiveIntegerField()
    allow_sharer = models.BooleanField(default=False)
    special_info = models.CharField('special requirement',max_length=200,blank=True)
    ride_status= models.CharField(max_length=1, choices=RideStatus.choices, default=RideStatus.OPEN)
    def get_absolute_url(self):
        return reverse('ridesharer:ride_list')
    def __str__(self):
        return "Owner: "+ self.owner.username+" Arrival time: " + str(self.require_arrival_time) + " dest: " + self.destination + " status: " + self.get_ride_status_display()

class ShareAction(models.Model):
    id = models.AutoField(primary_key = True)
    sharer = models.ForeignKey(User, on_delete=models.CASCADE,primary_key=False, related_name='share_actions')
    shared_ride = models.ForeignKey(Ride, on_delete=models.CASCADE,primary_key=False, related_name='sharing_actions')
    sharer_num = models.PositiveIntegerField(default = 1)
    def __str__(self):
        return "sharer: "+ self.sharer.username+" takes totally " + str(self.sharer_num) + " passengers to join the ride"

docker-deploy/web-app/ridesharer/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Vehicle,Ride
    
class createUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1','password2']

class updateUserForm(forms.ModelForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['email']

VEHICLE_TYPE1 = [
    ("S", "SUV"),
    ("M", "MiniBus"),
    ("B", "Baby Car"),
    ("N", "Normal Car")
]

VEHICLE_TYPE2 = [
    ("S", "SUV"),
    ("M", "MiniBus"),
    ("B", "Baby Car"),
    ("N", "Normal Car"),
    ("", "No requirement")
]

class updateVehicleForm(forms.ModelForm):

    vehicle_type = forms.CharField(max_length=1, widget=forms.widgets.Select(choices=VEHICLE_TYPE1))
    license_number = forms.CharField(max_length = 50)
    max_capacity = forms.IntegerField(initial = 1)
    special_info = forms.CharField(max_length = 100,required = False)
    class Meta:
        model = Vehicle
        fields = ['vehicle_type','license_number','max_capacity','special_info']

class updateRideForm(forms.ModelForm):    
    destination = forms.CharField(max_length=100)    
    require_arrival_time = forms.DateTimeField(help_text='Format: 2022-01-01 12:00')
    require_vehicle_type = forms.CharField(
        max_length=1, widget=forms.widgets.Select(choices=VEHICLE_TYPE2),required = False)
    passengers = forms.IntegerField(initial=1)
    special_info = forms.CharField(max_length=400, required=False)
    allow_sharer = forms.BooleanField(initial=False, required=False)
    class Meta:
        model = Ride
        fields = ['require_arrival_time','destination','passengers','require_vehicle_type','allow_sharer','special_info']

class sharableOrderSearchCreateForm(forms.Form):
    destination =  forms.CharField(max_length=100)
    earleist_arrival_time = forms.DateTimeField(help_text='Format: 2022-01-01 12:00')
    latetest_arrival_time = forms.DateTimeField(help_text='Format: 2022-01-01 12:00')
    passengers_num = forms.IntegerField(initial=1)
    

docker-deploy/web-app/ridesharer/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.core.mail import send_mail
from django.urls import reverse
from django.http import HttpResponse,HttpResponseRedirect
from django.utils import timezone
from django.db.models import Q

from django.views.generic.edit import CreateView
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required


from django.contrib import messages
from .forms import *
from .models import *
###############
#log in/out & register 
###############

def user_register(request):
    form = createUserForm()
    if request.method == 'POST':
        form = createUserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,"Account was create for  "+username)
            return HttpResponseRedirect('login')
        messages.success(request,"Invalid email address!")
    return render(request, 'ridesharer/register.html')

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request,username = username, password = password)
        if user is not None:
            login(request,user)
            return HttpResponseRedirect('home')
        else:
            messages.info(request, 'Username or password is uncorrect')
    context = {}
    return render(request, 'ridesharer/login.html', context)

def user_logout(request):
    logout(request)
    return HttpResponseRedirect('login')


###############
#user stuff
###############

@login_required(login_url='ridesharer:user_login')
def user_update(request):
    if request.method == 'POST':
        form = updateUserForm(request.POST, instance = request.user)
        if form.is_valid():
            form.save()
            email = form.cleaned_data.get('email')
            messages.success(request,"email changed to "+ email)
            return HttpResponseRedirect('user_info')
    form = updateUserForm(instance = request.user)
    name = request.user.username
    context = {'form':form,'name':name}
    return  render(request, 'ridesharer/user_info.html',context)


@login_required(login_url='ridesharer:user_login')
def user_home(request):
    name = request.user.username
    context = {'name':name}
    return render(request, 'ridesharer/home.html',context)

class driver_register(CreateView):
    model = Vehicle
    fields = ['vehicle_type', 'license_number', 'max_capacity', 'special_info']
    template_name = 'ridesharer/driver_register.html'
    def form_valid(self, form):
        form.instance.driver= self.request.user
        return super().form_valid(form)


class ride_create(CreateView):
    model = Ride
    fields = [ 'require_arrival_time','destination','passengers','require_vehicle_type','allow_sharer','special_info']
    template_name = 'ridesharer/ride_create.html'

    def form_valid(self, form):
        form.instance.owner= self.request.user
        form.instance.driver= None
        form.instance.ride_status = RideStatus.OPEN
        return super().form_valid(form)

@login_required(login_url='ridesharer:user_login')
def ride_delete(request, ride_id):
    ride = Ride.objects.filter(id=ride_id)[0] 
    ride.delete()
    messages.success(request,"Successfully delete ride!")
    return HttpResponseRedirect(reverse('ridesharer:ride_list'))

@login_required(login_url='ridesharer:user_login')
def ride_detail(request, ride_id):
    user = request.user.username
    ride = Ride.objects.filter(id=ride_id)[0] 
    owner = ride.owner.username
    require_arrival_time = ride.require_arrival_time
    destination = ride.destination
    passengers = ride.passengers
    allow_sharer = ride.allow_sharer
    require_vehicle_type = ride.get_require_vehicle_type_display()
    if ride.ride_status != 'C':
        #owner
        #post
        if request.method == 'POST':
            form = updateRideForm(request.POST, instance = ride)
            context = {'form':form, 'ride':ride}
            if form.is_valid():
                form.save()
                messages.success(request,"Ride status has been updated !")
                render(request, 'ridesharer/ride_modify.html',context)
            else:
                messages.warning(request,"Invalid input !")
        #get
        if ride.sharing_actions.all():
            share_actions = ride.sharing_actions.all()
            context ={'owner':owner,'share_actions':share_actions,'driver':"",'require_arrival_time':ride.require_arrival_time,'destination':ride.destination,'passengers':ride.passengers,'require_vehicle_type':ride.get_require_vehicle_type_display(),'allow_sharer':ride.allow_sharer,'special_info':ride.special_info,'ride_status':ride.get_ride_status_display(),'user':user}
            return  render(request, 'ridesharer/ride_detail.html',context)
        form = updateRideForm(instance = ride)
        context ={'form':form, 'ride':ride}
        return render(request, 'ridesharer/ride_modify.html',context)
    if request.method == 'POST':
        ride.ride_status = 'F'
        ride.save()
        rides = request.user.driver_ride.all().filter(ride_status=RideStatus.CONFIRMED)
        context = {
            'rides': rides,
        }
        return render(request, 'ridesharer/ride_info.html', context)
    driver = ride.driver.username
    vehicle_type = ride.driver.vehicle.vehicle_type
    license_number = ride.driver.vehicle.license_number
    max_capacity = ride.driver.vehicle.max_capacity
    special_info = ride.driver.vehicle.special_info
    try:
        share_actions = ride.sharing_actions.all()
        context ={'owner':owner,'share_actions':share_actions,'driver':driver,'require_arrival_time':ride.require_arrival_time,'destination':ride.destination,'passengers':ride.passengers,'require_vehicle_type':ride.get_require_vehicle_type_display(),'allow_sharer':ride.allow_sharer,'special_info':ride.special_info,'ride_status':ride.get_ride_status_display(),'vehicle_type': vehicle_type,'license_number': license_number,'max_capacity': max_capacity,'driver_special_info': special_info,'user':user}
        return  render(request, 'ridesharer/ride_detail.html',context)
    except AttributeError:
        context ={'owner':owner,'driver':driver,'require_arrival_time':ride.require_arrival_time,'destination':ride.destination,'passengers':ride.passengers,'require_vehicle_type':ride.get_require_vehicle_type_display(),'allow_sharer':ride.allow_sharer,'special_info':ride.special_info,'ride_status':ride.get_ride_status_display(),'vehicle_type': vehicle_type,'license_number': license_number,'max_capacity': max_capacity,'driver_special_info': special_info,'user':user}
        return  render(request, 'ridesharer/ride_detail.html',context)
# def user_update(request):
#     if request.method == 'POST':
#         form = updateUserForm(request.POST, instance = request.user)
#         if form.is_valid():
#             form.save()
#             email = form.cleaned_data.get('email')
#             messages.success(request,"email changed to "+ email)
#             return HttpResponseRedirect('user_info')
#     form = updateUserForm(instance = request.user)
#     name = request.user.username
#     context = {'form':form,'name':name}
#     return  render(request, 'ridesharer/user_info.html',context)

@login_required(login_url='ridesharer:user_login')
def ride_list(request):
    allRides = request.user.ride.all()
    rides = allRides.filter().exclude(ride_status=RideStatus.FINISH)
    context = {
        'rides': rides,
    }
    return render(request, 'ridesharer/ride_info.html', context)

@login_required(login_url='ridesharer:user_login')
def joined_ride_list(request):
    allActions = request.user.share_actions.all()
    rides = []
    for action in allActions:
        if action.shared_ride.ride_status != 'F':
            rides.append(action.shared_ride)
    context = {
        'rides': rides,
    }
    return render(request, 'ridesharer/joined_ride_list.html', context)

def joined_ride_detail(request, ride_id):
    ride = Ride.objects.filter(id=ride_id)[0]
    driver = "To be assigned"
    if request.method == 'POST':
        allActions = request.user.share_actions.all()
        for action in allActions:
            if action.shared_ride.id == ride_id:
                action.shared_ride.passengers -= action.sharer_num
                action.shared_ride.save()
                action.delete()
            return HttpResponseRedirect(reverse('ridesharer:joined_ride_list'))
    share_actions = ride.sharing_actions.all()
    ride_status = ride.get_ride_status_display()
    if ride_status != 'confirmed':
        context ={'ride_status':ride_status,'share_actions':share_actions,'driver':driver,'require_arrival_time':ride.require_arrival_time,'destination':ride.destination,'passengers':ride.passengers,'require_vehicle_type':ride.get_require_vehicle_type_display,'allow_sharer':ride.allow_sharer,'special_info':ride.special_info,'ride_status':ride_status}
        return  render(request, 'ridesharer/joined_ride_detail.html',context)
    driver = ride.driver.username
    vehicle_type = ride.driver.vehicle.get_vehicle_type_display()
    license_number = ride.driver.vehicle.license_number
    max_capacity = ride.driver.vehicle.max_capacity
    special_info = ride.driver.vehicle.special_info
    context ={'ride_status':ride_status,'share_actions':share_actions,'driver':driver,'require_arrival_time':ride.require_arrival_time,'destination':ride.destination,'passengers':ride.passengers,'require_vehicle_type':ride.get_require_vehicle_type_display(),'allow_sharer':ride.allow_sharer,'my_special_info':ride.special_info,'vehicle_type': vehicle_type,'license_number': license_number,'max_capacity': max_capacity,'driver_special_info': special_info}
    return  render(request, 'ridesharer/joined_ride_detail.html',context)

docker-deploy/web-app/ridesharer/templates/ridesharer/ride_confirm.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ridesharer register</title>
    <link href="{% static 'css/login.css' %}" rel="stylesheet" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-dark navbar-dark">
      <div class="container">
        <a href="#" class="navbar-brand">Order Ride</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navmenu"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navmenu">
          <ul class="navbar-nav ms-auto">
            <li class="nav-item">
              <a href="{% url 'ridesharer:user_home' %}" class="nav-link"
                >home</a
              >
            </li>
            <li class="nav-item">
              <a href="{% url 'ridesharer:ride_list' %}" class="nav-link"
                >your rides
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'ridesharer:joined_ride_list' %}" class="nav-link"
                >joined rides
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'ridesharer:order_list' %}" class="nav-link"
                >driver orders</a
              >
            </li>
            <li class="nav-item">
              <a href="{% url 'ridesharer:user_update' %}" class="nav-link"
                >user info</a
              >
            </li>
            <li class="nav-item">
              <a href="{% url 'ridesharer:vehicle_info' %}" class="nav-link"
                >vehicle info</a
              >
            </li>
            <li class="nav-item">
              <a href="{% url 'ridesharer:user_logout' %}" class="nav-link"
                >logout</a
              >
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <section class="vh-200 gradient-custom">
      <div class="container py-5 h-100">
        <div class="d-flex justify-content-center align-items-center h-150">
          <div class="col-12 col-md-8 col-lg-6 col-xl-5">
            <div class="card bg-dark text-white" style="border-radius: 1rem">
              <div class="card-body p-5 text-left">
                <form method="POST" action="">
                  {% csrf_token%}
                  <div class="mb-md-3 mt-md-4 pb-5">
                    <h2 class="fw-bold mb-4 text-uppercase">Order your ride</h2>
                    <br />
                    <p>
                      <label for="id_destination">driver:</label>
                      {{driver}}
                    </p>
                    <p>
                      <label for="id_require_arrival_time"
                        >Require arrival time:</label
                      >
                      {{require_arrival_time}}
                    </p>

                    <p>
                      <label for="id_destination">Destination:</label>
                      {{destination}}
                    </p>

                    <p>
                      <label for="id_passengers">passengers:</label>
                      {{passengers}}
                    </p>

                    <p>
                      <label for="id_require_vehicle_type"
                        >Require vehicle type:</label
                      >
                      {{require_vehicle_type}}
                    </p>

                    <p>
                      <label for="id_allow_sharer">Allow sharer:</label>
                      {{allow_sharer}}
                    </p>

                    <p>
                      <label for="id_special_info">Special info:</label>
                      {{special_info}}
                    </p>
                    <br />

                    <!-- <div class="form-white mb-2">
                        <label class="form-label" for="typeNameX"></label>
                        <br />
                        <input
                          type="text"
                          name="username"
                          maxlength="150"
                          autofocus=""
                          required=""
                          id="id_username"
                          class="form-control-lg"
                        />
                      </div>
  
                      <div class="form-white mb-2">
                        <label class="form-label" for="typeEmailX">Email</label>
                        <br />
                        <input
                          type="email"
                          name="email"
                          maxlength="254"
                          id="id_email"
                          class="form-control-lg"
                        />
                      </div>
  
                      <div class="form-white mb-2">
                        <label class="form-label" for="typePasswordX"
                          >Password</label
                        >
                        <br />
                        <input
                          type="password"
                          name="password1"
                          autocomplete="new-password"
                          required=""
                          id="id_password1"
                          class="form-control-lg"
                        />
                      </div> -->
                    {% if ride_status == 'open'%}
                    <button
                      class="btn btn-outline-light btn-lg px-5"
                      type="submit"
                      name="Confirm order"
                    >
                      Confirm ride
                    </button>
                    {% else %}
                    <p>
                      <label for="id_special_info">Special info:</label>
                      {{ride_status}}
                    </p>
                    {% endif %}
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

docker-deploy/web-app/ridesharer/templates/ridesharer/ride_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ridesharer register</title>
    <link href="{% static 'css/login.css' %}" rel="stylesheet" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-dark navbar-dark">
      <div class="container">
        <a href="#" class="navbar-brand">Ride Details</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navmenu"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navmenu">
          <ul class="navbar-nav ms-auto">
            <li class="nav-item">
              <a href="{% url 'ridesharer:user_home' %}" class="nav-link"
                >home</a
              >
            </li>
            <li class="nav-item">
              <a href="{% url 'ridesharer:ride_list' %}" class="nav-link"
                >your rides
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'ridesharer:joined_ride_list' %}" class="nav-link"
                >joined rides
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'ridesharer:order_list' %}" class="nav-link"
                >driver orders</a
              >
            </li>
            <li class="nav-item">
              <a href="{% url 'ridesharer:user_update' %}" class="nav-link"
                >user info</a
              >
            </li>
            <li class="nav-item">
              <a href="{% url 'ridesharer:vehicle_info' %}" class="nav-link"
                >vehicle info</a
              >
            </li>
            <li class="nav-item">
              <a href="{% url 'ridesharer:user_logout' %}" class="nav-link"
                >logout</a
              >
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <section class="vh-200 gradient-custom">
      <div class="container py-5 h-100">
        <div class="d-flex justify-content-center align-items-center h-150">
          <div class="col-12 col-md-8 col-lg-6 col-xl-5">
            <div class="card bg-dark text-white" style="border-radius: 1rem">
              <div class="card-body p-5 text-left">
                <form method="POST" action="">
                  {% csrf_token %}
                  <div class="mb-md-3 mt-md-4 pb-5">
                    <h2 class="fw-bold mb-4 text-uppercase">Ride details</h2>
                    <br />
                    {% if owner == user and ride_status == 'confirmed'%}
                    <h2>Vehicle Information</h2>
                    <br />
                    <p>
                      <label for="id_driver">Driver:</label>
                      {{driver}}
                    </p>
                    <p>
                      <label for="id_vehicle_type">Vehicle type:</label>
                      {{vehicle_type}}
                    </p>
                    <p>
                      <label for="id_license_number">license number:</label>
                      {{license_number}}
                    </p>
                    <p>
                      <label for="id_max_capacity">Max capacity: </label>
                      {{max_capacity}}
                    </p>
                    <p>
                      <label for="id_driver_special_info">Special info: </label>
                      {{driver_special_info}}
                    </p>
                    {% endif %}
                    <h2>Ride Information</h2>
                    <p>
                      <label for="id_require_arrival_time"
                        >Require arrival time:</label
                      >
                      {{require_arrival_time}}
                    </p>

                    <p>
                      <label for="id_destination">Destination:</label>
                      {{destination}}
                    </p>

                    <p>
                      <label for="id_passengers">passengers:</label>
                      {{passengers}}
                    </p>

                    <p>
                      <label for="id_require_vehicle_type"
                        >Require vehicle type:</label
                      >
                      {{require_vehicle_type}}
                    </p>

                    <p>
                      <label for="id_allow_sharer">Allow sharer:</label>
                      {{allow_sharer}}
                    </p>

                    <p>
                      <label for="id_special_info">Owner's special info:</label>
                      {{special_info}}
                    </p>
                    <!-- <div class="form-white mb-2">
                        <label class="form-label" for="typeNameX"></label>
                        <br />
                        <input
                          type="text"
                          name="username"
                          maxlength="150"
                          autofocus=""
                          required=""
                          id="id_username"
                          class="form-control-lg"
                        />
                      </div>
  
                      <div class="form-white mb-2">
                        <label class="form-label" for="typeEmailX">Email</label>
                        <br />
                        <input
                          type="email"
                          name="email"
                          maxlength="254"
                          id="id_email"
                          class="form-control-lg"
                        />
                      </div>
  
                      <div class="form-white mb-2">
                        <label class="form-label" for="typePasswordX"
                          >Password</label
                        >
                        <br />
                        <input
                          type="password"
                          name="password1"
                          autocomplete="new-password"
                          required=""
                          id="id_password1"
                          class="form-control-lg"
                        />
                      </div> -->
                    {% for share_action in share_actions %}
                    <li>{{ share_action}}</li>
                    {% endfor %} {% if driver == user%}
                    <button
                      class="btn btn-outline-light btn-lg px-5"
                      type="submit"
                      name="Finish Order"
                    >
                      Finish
                    </button>
                    {% endif %}
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
      crossorigin="anonymous"
    ></script>
  </body>
</html>